// SERVER
export const SEND_NEW_ARTICLE = 'SEND_NEW_ARTICLE'
export const SEND_NEW_ARTICLE_SUCCESS = 'SEND_NEW_ARTICLE_SUCCESS'
export const SEND_NEW_ARTICLE_DENY = 'SEND_NEW_ARTICLE_DENY'

export const GET_ARTICLE_DATA_FOR_INPUT = 'GET_ARTICLE_DATA_FOR_INPUT'
export const GET_ARTICLE_DATA_FOR_INPUT_DENY = 'GET_ARTICLE_DATA_FOR_INPUT_DENY'
export const GET_ARTICLE_DATA_FOR_INPUT_SUCCESS = 'GET_ARTICLE_DATA_FOR_INPUT_SUCCESS'

// SEND ARTICLE TEXT FROM Inputs
export const SEND_SEARCH_TEXT = 'SEND_SEARCH_TEXT'
export const GET_INPUT_DATA = 'GET_INPUT_DATA'
export const GET_INPUT_DATA_DONE = 'GET_INPUT_DATA_DONE'

// SUBMITaRTICLE
export const SEND_INPUT_DATA_CHANGED = 'SEND_INPUT_DATA_CHANGED'

// HEADER COMPONENT ============================================================
export const SEND_INPUT_DATA_CHANGED_DATE = 'SEND_INPUT_DATA_CHANGED_DATE'
export const SEND_INPUT_DATA_CHANGED_NAME = 'SEND_INPUT_DATA_CHANGED_NAME'
export const SEND_INPUT_DATA_CHANGED_NAMEID = 'SEND_INPUT_DATA_CHANGED_NAMEID'
export const SEND_INPUT_DATA_CHANGED_FULLTIME = 'SEND_INPUT_DATA_CHANGED_FULLTIME'
export const SEND_INPUT_DATA_CHANGED_RATE_WEEKDAY = 'SEND_INPUT_DATA_CHANGED_RATE_WEEKDAY'
export const SEND_INPUT_DATA_CHANGED_RATE_WEEKEND = 'SEND_INPUT_DATA_CHANGED_RATE_WEEKEND'

// MAIN COMPONENT ==============================================================
export const SEND_INPUT_DATA_CHANGED_ARTICLE = 'SEND_INPUT_DATA_CHANGED_ARTICLE'
export const SEND_INPUT_DATA_CHANGED_TIME = 'SEND_INPUT_DATA_CHANGED_TIME'
export const SEND_INPUT_DATA_CHANGED_AMOUNT = 'SEND_INPUT_DATA_CHANGED_AMOUNT'
export const SEND_INPUT_DATA_CHANGED_BOXES = 'SEND_INPUT_DATA_CHANGED_BOXES'
export const SEND_INPUT_DATA_CHANGED_INBOX = 'SEND_INPUT_DATA_CHANGED_INBOX'

// SEND ERROR STATUS
export const SEND_ERROR_STATUS_HEADER = 'SEND_ERROR_STATUS_HEADER'
export const SEND_ERROR_STATUS_MAIN = 'SEND_ERROR_STATUS_MAIN'

// ACTION WITH FORMS
export const ADD_NEWA_ARTICLE_INPUT_FORM = 'ADD_NEWA_ARTICLE_INPUT_FORM'
export const REMOVE_LAST_ARTICLE_INPUT_FORM = 'REMOVE_LAST_ARTICLE_INPUT_FORM'

// TableArticle Actions:
export const CLEAR_ALL_INPUT_DATA_MAIN = 'CLEAR_ALL_INPUT_DATA_MAIN'
export const CLEAR_ALL_INPUT_DATA_HEADER = 'CLEAR_ALL_INPUT_DATA_HEADER'
