export const GET_TABLE_ARTICLE_DATA = 'GET_TABLE_ARTICLE_DATA'
export const GET_TABLE_ARTICLE_DATA_SUCCESS = 'GET_TABLE_ARTICLE_DATA_SUCCESS'
export const GET_TABLE_ARTICLE_DATA_DENY = 'GET_TABLE_ARTICLE_DATA_DENY'

export const UPDATE_SELECTED_ARTICLE_IN_DB = 'UPDATE_SELECTED_ARTICLE_IN_DB'
export const UPDATE_SELECTED_ARTICLE_IN_DB_SUCCESS = 'UPDATE_SELECTED_ARTICLE_IN_DB_SUCCESS'
export const UPDATE_SELECTED_ARTICLE_IN_DB_DENY = 'UPDATE_SELECTED_ARTICLE_IN_DB_DENY'

export const DELET_SELECTED_ARTICLE_IN_DB = 'DELET_SELECTED_ARTICLE_IN_DB'
export const DELET_SELECTED_ARTICLE_IN_DB_SUCCESS = 'DELET_SELECTED_ARTICLE_IN_DB_SUCCESS'
export const DELET_SELECTED_ARTICLE_IN_DB_DENY = 'DELET_SELECTED_ARTICLE_IN_DB_DENY'

// FILTER
export const FILTER_INPUT_CHANGED_NAME = 'FILTER_INPUT_CHANGED_NAME'
export const FILTER_INPUT_CHANGED_DATE_FROM = 'FILTER_INPUT_CHANGED_DATE_FROM'
export const FILTER_INPUT_CHANGED_DATE_TO = 'FILTER_INPUT_CHANGED_DATE_TO'
export const FILTER_INPUT_CHANGED_ARTICLE = 'FILTER_INPUT_CHANGED_ARTICLE'

// SELECT
export const SEND_CURRENT_SELECTED_ROW = 'SEND_CURRENT_SELECTED_ROW'
